import { IconDefinition } from '@ant-design/icons-angular';
import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  BellOutline,
  InfoCircleOutline,
  BgColorsOutline,
  OrderedListOutline,
  ExpandAltOutline,
  SlackOutline,
  GiftOutline,
  FormatPainterOutline,
  ShoppingCartOutline,
  ShopOutline,
  ExclamationCircleOutline,
  BarChartOutline,
  MessageOutline,
  SendOutline,
  CloseOutline,
  FileTextOutline
} from '@ant-design/icons-angular/icons';

export const icons: IconDefinition[] = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  BellOutline,
  InfoCircleOutline,
  BgColorsOutline,
  OrderedListOutline,
  ExpandAltOutline,
  SlackOutline,
  FormatPainterOutline,
  GiftOutline,
  ShoppingCartOutline,
  ShopOutline,
  ExclamationCircleOutline,
  BarChartOutline,
  MessageOutline,
  SendOutline,
  CloseOutline,
  FileTextOutline
];
